package cool.klass.generator.dropwizard;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Objects;

import javax.annotation.Nonnull;

import cool.klass.model.meta.domain.api.DomainModel;
import cool.klass.model.meta.domain.api.service.ServiceGroup;

public class AbstractApplicationGenerator
{
    @Nonnull
    private final DomainModel domainModel;
    @Nonnull
    private final String      rootPackageName;
    @Nonnull
    private final String      applicationName;
    @Nonnull
    private final Instant     now;
    @Nonnull
    private final String      packageName;
    @Nonnull
    private final String      relativePath;

    public AbstractApplicationGenerator(
            @Nonnull DomainModel domainModel,
            @Nonnull String rootPackageName,
            @Nonnull String applicationName,
            @Nonnull Instant now)
    {
        this.domainModel = Objects.requireNonNull(domainModel);
        this.rootPackageName = Objects.requireNonNull(rootPackageName);
        this.applicationName = Objects.requireNonNull(applicationName);
        this.packageName = rootPackageName + ".dropwizard.application";
        this.now = now;
        this.relativePath = this.packageName.replaceAll("\\.", "/");
    }

    public void writeAbstractApplicationFile(@Nonnull Path outputPath) throws IOException
    {
        Path path = outputPath.resolve(this.relativePath);
        path.toFile().mkdirs();
        Path javaPath = path.resolve("Abstract" + this.applicationName + "Application.java");

        // @formatter:off
        //language=JAVA
        String sourceCode = ""
                + "package " + this.packageName + ";\n"
                + "\n"
                + "import javax.annotation.Generated;\n"
                + "\n"
                + "import cool.klass.dropwizard.application.AbstractKlassApplication;\n"
                + "import " + this.rootPackageName + ".service.resource.*;\n"
                + "import io.dropwizard.setup.Environment;\n"
                + "import klass.model.meta.domain.service.resource.*;\n"
                + "import org.slf4j.Logger;\n"
                + "import org.slf4j.LoggerFactory;\n"
                + "\n"
                + "/**\n"
                + " * Auto-generated by {@link cool.klass.generator.dropwizard.AbstractApplicationGenerator}\n"
                + " */\n"
                + "@Generated(\n"
                + "        value = \"cool.klass.generator.dropwizard.AbstractApplicationGenerator\",\n"
                + "        date = \"" + this.now + "\")\n"
                + "public abstract class Abstract" + this.applicationName + "Application extends AbstractKlassApplication<" + this.applicationName + "Configuration>\n"
                + "{\n"
                + "    private static final Logger LOGGER = LoggerFactory.getLogger(Abstract" + this.applicationName + "Application.class);\n"
                + "\n"
                + "    public Abstract" + this.applicationName + "Application()\n"
                + "    {\n"
                + "        super(\"" + this.applicationName + "\");\n"
                + "    }\n"
                + "\n"
                + "    @Override\n"
                + "    public void run(\n"
                + "            " + this.applicationName + "Configuration configuration,\n"
                + "            Environment environment) throws Exception\n"
                + "    {\n"
                + "        super.run(configuration, environment);\n"
                + "        \n"
                + "\n"
                + this.getRegisterResourcesSourceCode()
                + "    }\n"
                + "}\n";
        // @formatter:on

        this.printStringToFile(javaPath, sourceCode);
    }

    private String getRegisterResourcesSourceCode()
    {
        return this.domainModel
                .getServiceGroups()
                .collect(this::getRegisterResourceSourceCode)
                .makeString("");
    }

    private String getRegisterResourceSourceCode(@Nonnull ServiceGroup serviceGroup)
    {
        return String.format(
                "        environment.jersey().register(new %sResource(this.dataStore, this.clock));\n",
                serviceGroup.getKlass().getName());
    }

    private void printStringToFile(@Nonnull Path path, String contents) throws FileNotFoundException
    {
        try (PrintStream printStream = new PrintStream(new FileOutputStream(path.toFile())))
        {
            printStream.print(contents);
        }
    }
}
