package klass.model.meta.domain.dropwizard.test;

import java.util.concurrent.TimeUnit;

import javax.annotation.Nonnull;
import javax.ws.rs.client.Client;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

import cool.klass.model.converter.bootstrap.writer.KlassBootstrapWriter;
import cool.klass.reladomo.test.rule.ReladomoTestRule;
import io.dropwizard.client.JerseyClientBuilder;
import io.dropwizard.client.JerseyClientConfiguration;
import io.dropwizard.testing.ResourceHelpers;
import io.dropwizard.testing.junit.DropwizardAppRule;
import io.dropwizard.util.Duration;
import klass.model.meta.domain.dropwizard.application.KlassBootstrappedMetaModelApplication;
import klass.model.meta.domain.dropwizard.application.KlassBootstrappedMetaModelConfiguration;
import org.json.JSONException;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.skyscreamer.jsonassert.JSONCompareMode;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AssociationResourceManualTest
{
    @ClassRule
    public static final DropwizardAppRule<KlassBootstrappedMetaModelConfiguration> RULE = new DropwizardAppRule<>(
            KlassBootstrappedMetaModelApplication.class,
            ResourceHelpers.resourceFilePath("config-test.yml"));

    @Rule
    public final ReladomoTestRule reladomoTestRule = new ReladomoTestRule(
            "reladomo-runtime-configuration/TestReladomoRuntimeConfiguration.xml")
            .transactionTimeout(5, TimeUnit.MINUTES);

    protected Client getClient(String clientName)
    {
        JerseyClientConfiguration jerseyClientConfiguration = new JerseyClientConfiguration();
        jerseyClientConfiguration.setTimeout(Duration.minutes(5));

        return new JerseyClientBuilder(RULE.getEnvironment())
                .using(jerseyClientConfiguration)
                .build(clientName);
    }

    @Before
    public void bootstrap()
    {
        KlassBootstrappedMetaModelApplication application = RULE.getApplication();

        KlassBootstrapWriter klassBootstrapWriter = new KlassBootstrapWriter(
                application.getDomainModel(),
                application.getDataStore());
        klassBootstrapWriter.bootstrapMetaModel();
    }

    @Test
    public void getAllMeta() throws JSONException
    {
        Client client = this.getClient(
                "klass.model.meta.domain.dropwizard.test.AssociationResourceManualTest.getAllMeta");

        Response response = client.target(
                String.format("http://localhost:%d/api/meta/association", RULE.getLocalPort()))
                .request()
                .get();

        this.assertResponseStatus(response, Status.OK);

        String jsonResponse = response.readEntity(String.class);
        //language=JSON
        String expected = ""
                + "[\n"
                + "  {\n"
                + "    \"name\": \"EnumerationPropertyHasEnumeration\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"enumerationProperty\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"EnumerationProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"enumeration\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Enumeration\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"EnumerationProperty\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"enumerationName\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Enumeration\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassHasSuperClass\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"subClasses\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"superClass\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"superClassName\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassifierHasPrimitiveProperties\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClassifier\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"primitiveProperties\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"PrimitiveProperty\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"PrimitiveProperty\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"classifierName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassifierHasEnumerationProperties\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClassifier\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"enumerationProperties\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"EnumerationProperty\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"EnumerationProperty\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"classifierName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassifierHasClassifierInterfaceMapping\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"subClassifier\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"superInterfaces\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ClassifierInterfaceMapping\"\n"
                + "        },\n"
                + "        \"associationEndModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"owned\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ClassifierInterfaceMapping\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"classifierName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"EnumerationHasLiterals\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"enumeration\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Enumeration\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"enumerationLiterals\",\n"
                + "        \"multiplicity\": \"1..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"EnumerationLiteral\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Enumeration\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"EnumerationLiteral\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"enumerationName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassifierInterfaceMappingHasInterface\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"superInterface\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Interface\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"subClassifiers\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ClassifierInterfaceMapping\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Interface\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ClassifierInterfaceMapping\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"interfaceName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationEndHasResultType\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"associationEndsResultTypeOf\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"resultType\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"resultTypeName\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassHasAssociationEnds\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClass\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"owningClassName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassifierHasModifiers\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClassifier\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"classifierModifiers\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ClassifierModifier\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Classifier\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ClassifierModifier\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"classifierName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"DataTypePropertyHasModifiers\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"DataTypeProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"propertyModifiers\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"PropertyModifier\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"PropertyModifier\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"PropertyModifier\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"propertyName\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationHasEnds\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"owningAssociation\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Association\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Association\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"associationName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MemberReferencePathHasEdgePointCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"memberReferencePath\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MemberReferencePath\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"edgePointCriteria\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"EdgePointCriteria\"\n"
                + "        },\n"
                + "        \"associationEndModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"owned\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"MemberReferencePath\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"id\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"EdgePointCriteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"memberReferencePathId\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"OperatorCriteriaHasTargetExpressionValue\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"operatorCriteriaTargetOf\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"OperatorCriteria\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"targetExpressionValue\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ExpressionValue\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"OperatorCriteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"targetExpressionId\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ExpressionValue\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"id\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MemberReferencePathHasMemberReferencePathAssociationEndMapping\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"memberReferencePath\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MemberReferencePath\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MemberReferencePathAssociationEndMapping\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"MemberReferencePath\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"id\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"MemberReferencePathAssociationEndMapping\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"memberReferencePathId\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationHasCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"association\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Association\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"criteria\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Criteria\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Association\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"criteriaId\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Criteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"id\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationEndHasModifiers\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"associationEnd\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEndModifiers\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEndModifier\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEnd\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"owningClassName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEndModifier\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"owningClassName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEnd\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEndModifier\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"associationEndName\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MemberReferencePathHasClass\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"memberReferencePaths\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MemberReferencePath\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"klass\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"MemberReferencePath\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"className\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"OperatorCriteriaHasSourceExpressionValue\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"operatorCriteriaSourceOf\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"OperatorCriteria\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"sourceExpressionValue\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ExpressionValue\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"OperatorCriteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"sourceExpressionId\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ExpressionValue\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"id\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ParameterizedPropertyHasResultType\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"parameterizedPropertiesResultTypeOf\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ParameterizedProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"resultType\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ParameterizedProperty\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"resultTypeName\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassHasParameterizedProperties\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClass\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"parameterizedProperties\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ParameterizedProperty\"\n"
                + "        },\n"
                + "        \"associationEndModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"owned\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ParameterizedProperty\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"owningClassName\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"BinaryCriteraHasLeft\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"ownerOfLeftCriteria\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"BinaryCriteria\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"left\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Criteria\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"BinaryCriteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"leftId\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Criteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"id\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"DataTypePropertyHasMemberReferencePaths\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"memberReferencePaths\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MemberReferencePath\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"DataTypeProperty\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MemberReferencePath\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"propertyClassName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MemberReferencePath\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"propertyName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"BinaryCriteraHasRight\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"ownerOfRightCriteria\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"BinaryCriteria\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"right\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Criteria\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"BinaryCriteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"rightId\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Criteria\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"id\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ServiceGroupHasUrls\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"serviceGroup\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ServiceGroup\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"urls\",\n"
                + "        \"multiplicity\": \"1..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Url\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ServiceGroup\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"className\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Url\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"className\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ServiceGroupHasClass\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"serviceGroup\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ServiceGroup\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"owningClass\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"OperatorCriteria\",\n"
                + "      \"operator\": \"==\",\n"
                + "      \"sourceExpressionValue\": {\n"
                + "        \"_type\": \"ThisMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"ServiceGroup\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"className\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"targetExpressionValue\": {\n"
                + "        \"_type\": \"TypeMemberReferencePath\",\n"
                + "        \"klass\": {\n"
                + "          \"name\": \"Klass\"\n"
                + "        },\n"
                + "        \"dataTypeProperty\": {\n"
                + "          \"name\": \"name\"\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ParameterizedPropertyHasParameters\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"parameterizedProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ParameterizedProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"parameters\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ParameterizedPropertyParameter\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"owningClassName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedPropertyParameter\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedPropertyParameter\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"parameterizedPropertyName\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"UrlHasServices\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"url\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Url\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"services\",\n"
                + "        \"multiplicity\": \"1..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"Service\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"Url\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"className\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"Service\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"className\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"Url\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"url\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"Service\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"urlString\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ParameterizedPropertyHasOrdering\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"parameterizedProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ParameterizedProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"parameterizedPropertyOrdering\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"ParameterizedPropertyOrdering\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"owningClassName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedPropertyOrdering\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"owningClassName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"ParameterizedPropertyOrdering\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationEndHasOrdering\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"associationEnd\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEndOrdering\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEndOrdering\"\n"
                + "        },\n"
                + "        \"associationEndModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"owned\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEnd\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"associationName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEndOrdering\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"associationName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEnd\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"direction\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEndOrdering\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"direction\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MemberReferencePathAssociationEndMappingHasAssociationEnd\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"memberReferencePaths\",\n"
                + "        \"multiplicity\": \"0..*\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MemberReferencePathAssociationEndMapping\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEnd\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"AssociationEnd\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MemberReferencePathAssociationEndMapping\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"associationOwningClassName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEnd\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"owningClassName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MemberReferencePathAssociationEndMapping\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"associationEndName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"AssociationEnd\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"PrimitivePropertyHasMaxPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"primitiveProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"PrimitiveProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"maxValidation\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MaxPropertyValidation\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"PrimitiveProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MaxPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"PrimitiveProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MaxPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"propertyName\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"PrimitivePropertyHasMinPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"primitiveProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"PrimitiveProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"minValidation\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MinPropertyValidation\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"PrimitiveProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MinPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"PrimitiveProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MinPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"propertyName\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"DataTypePropertyHasMaxLengthPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"DataTypeProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"maxLengthValidation\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MaxLengthPropertyValidation\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MaxLengthPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MaxLengthPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"propertyName\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"DataTypePropertyHasMinLengthPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"associationEnds\": [\n"
                + "      {\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"multiplicity\": \"1..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"DataTypeProperty\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"minLengthValidation\",\n"
                + "        \"multiplicity\": \"0..1\",\n"
                + "        \"resultType\": {\n"
                + "          \"name\": \"MinLengthPropertyValidation\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"criteria\": {\n"
                + "      \"_type\": \"AndCriteria\",\n"
                + "      \"left\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MinLengthPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"classifierName\"\n"
                + "          }\n"
                + "        }\n"
                + "      },\n"
                + "      \"right\": {\n"
                + "        \"_type\": \"OperatorCriteria\",\n"
                + "        \"operator\": \"==\",\n"
                + "        \"sourceExpressionValue\": {\n"
                + "          \"_type\": \"ThisMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"DataTypeProperty\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"targetExpressionValue\": {\n"
                + "          \"_type\": \"TypeMemberReferencePath\",\n"
                + "          \"klass\": {\n"
                + "            \"name\": \"MinLengthPropertyValidation\"\n"
                + "          },\n"
                + "          \"dataTypeProperty\": {\n"
                + "            \"name\": \"propertyName\"\n"
                + "          }\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "  }\n"
                + "]";
        JSONAssert.assertEquals(expected, jsonResponse, JSONCompareMode.STRICT);
    }

    public void assertResponseStatus(@Nonnull Response response, Status status)
    {
        response.bufferEntity();
        String entityAsString = response.readEntity(String.class);
        assertThat(entityAsString, response.getStatusInfo(), is(status));
    }
}
