package klass.model.meta.domain.dropwizard.test;

import java.util.concurrent.TimeUnit;

import javax.annotation.Nonnull;
import javax.ws.rs.client.Client;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

import cool.klass.model.converter.bootstrap.writer.KlassBootstrapWriter;
import cool.klass.reladomo.test.rule.ReladomoTestRule;
import io.dropwizard.client.JerseyClientBuilder;
import io.dropwizard.client.JerseyClientConfiguration;
import io.dropwizard.testing.ResourceHelpers;
import io.dropwizard.testing.junit.DropwizardAppRule;
import io.dropwizard.util.Duration;
import klass.model.meta.domain.dropwizard.application.KlassBootstrappedMetaModelApplication;
import klass.model.meta.domain.dropwizard.application.KlassBootstrappedMetaModelConfiguration;
import org.json.JSONException;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.skyscreamer.jsonassert.JSONCompareMode;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class ClassResourceManualTest
{
    @ClassRule
    public static final DropwizardAppRule<KlassBootstrappedMetaModelConfiguration> RULE = new DropwizardAppRule<>(
            KlassBootstrappedMetaModelApplication.class,
            ResourceHelpers.resourceFilePath("config-test.yml"));

    @Rule
    public final ReladomoTestRule reladomoTestRule = new ReladomoTestRule(
            "reladomo-runtime-configuration/TestReladomoRuntimeConfiguration.xml")
            .transactionTimeout(5, TimeUnit.MINUTES);

    protected Client getClient(String clientName)
    {
        JerseyClientConfiguration jerseyClientConfiguration = new JerseyClientConfiguration();
        jerseyClientConfiguration.setTimeout(Duration.minutes(5));

        return new JerseyClientBuilder(RULE.getEnvironment())
                .using(jerseyClientConfiguration)
                .build(clientName);
    }

    @Before
    public void bootstrap()
    {
        KlassBootstrappedMetaModelApplication application = RULE.getApplication();

        KlassBootstrapWriter klassBootstrapWriter = new KlassBootstrapWriter(
                application.getDomainModel(),
                application.getDataStore());
        klassBootstrapWriter.bootstrapMetaModel();
    }

    @Test
    public void getAllMeta() throws JSONException
    {
        Client client = this.getClient(
                "klass.model.meta.domain.dropwizard.test.ClassResourceManualTest.getAllMeta");

        Response response = client.target(
                String.format("http://localhost:%d/api/meta/class", RULE.getLocalPort()))
                .request()
                .get();

        this.assertResponseStatus(response, Status.OK);

        String jsonResponse = response.readEntity(String.class);
        //language=JSON
        String expected = ""
                + "[\n"
                + "  {\n"
                + "    \"name\": \"Enumeration\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"PackageableElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"EnumerationLiteral\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"enumerationName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"prettyName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": true,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"Classifier\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"PackageableElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"Interface\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"Classifier\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassifierInterfaceMapping\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"classifierName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"interfaceName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"Klass\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"Classifier\"\n"
                + "    },\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"superClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": true,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"inheritanceType\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"InheritanceType\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"DataTypeProperty\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"classifierName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"optional\",\n"
                + "        \"primitiveType\": \"Boolean\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"key\",\n"
                + "        \"primitiveType\": \"Boolean\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"PrimitiveProperty\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"DataTypeProperty\"\n"
                + "    },\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"id\",\n"
                + "        \"primitiveType\": \"Boolean\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"primitiveType\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"PrimitiveType\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"EnumerationProperty\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"DataTypeProperty\"\n"
                + "    },\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"enumerationName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"NumericPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"PropertyValidation\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"classifierName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"propertyName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"number\",\n"
                + "        \"primitiveType\": \"Integer\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MinLengthPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"NumericPropertyValidation\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MaxLengthPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"NumericPropertyValidation\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MinPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"NumericPropertyValidation\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MaxPropertyValidation\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"NumericPropertyValidation\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"PropertyModifier\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"classifierName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"propertyName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ClassifierModifier\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"classifierName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"Association\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"PackageableElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"criteriaId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationEnd\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"resultTypeName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"direction\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"AssociationEndDirection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"multiplicity\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"Multiplicity\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationEndModifier\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEndName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"Criteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"Element\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"id\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": true,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"id\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AllCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"Criteria\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"BinaryCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"Criteria\"\n"
                + "    },\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"leftId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"rightId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AndCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"BinaryCriteria\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"OrCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"BinaryCriteria\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"OperatorCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"Criteria\"\n"
                + "    },\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"sourceExpressionId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"targetExpressionId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"operator\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"Operator\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"EdgePointCriteria\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"Criteria\"\n"
                + "    },\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"memberReferencePathId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ExpressionValue\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"id\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": true,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"id\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MemberReferencePath\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"ExpressionValue\"\n"
                + "    },\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"className\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"propertyClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"propertyName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"MemberReferencePathAssociationEndMapping\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"memberReferencePathId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationOwningClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEndName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ThisMemberReferencePath\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"MemberReferencePath\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"TypeMemberReferencePath\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superClass\": {\n"
                + "      \"name\": \"MemberReferencePath\"\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ParameterizedProperty\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"resultTypeName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"multiplicity\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"Multiplicity\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationEndOrderBy\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"associationEndClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"associationEndName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"thisMemberReferencePathId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"orderByDirection\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"OrderByDirection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"AssociationEndOrdering\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"associationName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"name\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"inferred\",\n"
                + "        \"primitiveType\": \"Boolean\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"orderingId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"multiplicity\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"Multiplicity\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"direction\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"AssociationEndDirection\"\n"
                + "        },\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ParameterizedPropertyOrdering\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"owningClassName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"name\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"inferred\",\n"
                + "        \"primitiveType\": \"Boolean\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"orderingId\",\n"
                + "        \"primitiveType\": \"Long\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ParameterizedPropertyParameter\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"superInterfaces\": [\n"
                + "      {\n"
                + "        \"superInterface\": {\n"
                + "          \"name\": \"NamedElement\"\n"
                + "        }\n"
                + "      }\n"
                + "    ],\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"classifierName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"name\": \"private\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"parameterizedPropertyName\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"Service\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"className\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"urlString\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enumerationProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"verb\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"Verb\"\n"
                + "        },\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"serviceMultiplicity\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": false,\n"
                + "        \"enumeration\": {\n"
                + "          \"name\": \"ServiceMultiplicity\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"Url\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"className\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"url\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"name\": \"ServiceGroup\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"primitiveProperties\": [\n"
                + "      {\n"
                + "        \"name\": \"className\",\n"
                + "        \"primitiveType\": \"String\",\n"
                + "        \"optional\": false,\n"
                + "        \"key\": true,\n"
                + "        \"id\": false,\n"
                + "        \"propertyModifiers\": [\n"
                + "          {\n"
                + "            \"name\": \"key\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  }\n"
                + "]";
        JSONAssert.assertEquals(expected, jsonResponse, JSONCompareMode.STRICT);
    }

    public void assertResponseStatus(@Nonnull Response response, Status status)
    {
        response.bufferEntity();
        String entityAsString = response.readEntity(String.class);
        assertThat(entityAsString, response.getStatusInfo(), is(status));
    }
}
