package klass.model.meta.domain.dropwizard.test;

import java.util.concurrent.TimeUnit;

import javax.annotation.Nonnull;
import javax.ws.rs.client.Client;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

import cool.klass.model.converter.bootstrap.writer.KlassBootstrapWriter;
import cool.klass.reladomo.test.rule.ReladomoTestRule;
import io.dropwizard.client.JerseyClientBuilder;
import io.dropwizard.client.JerseyClientConfiguration;
import io.dropwizard.testing.ResourceHelpers;
import io.dropwizard.testing.junit.DropwizardAppRule;
import io.dropwizard.util.Duration;
import klass.model.meta.domain.dropwizard.application.KlassBootstrappedMetaModelApplication;
import klass.model.meta.domain.dropwizard.application.KlassBootstrappedMetaModelConfiguration;
import org.json.JSONException;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.skyscreamer.jsonassert.JSONCompareMode;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class ProjectionResourceManualTest
{
    @ClassRule
    public static final DropwizardAppRule<KlassBootstrappedMetaModelConfiguration> RULE = new DropwizardAppRule<>(
            KlassBootstrappedMetaModelApplication.class,
            ResourceHelpers.resourceFilePath("config-test.yml"));

    @Rule
    public final ReladomoTestRule reladomoTestRule = new ReladomoTestRule(
            "reladomo-runtime-configuration/TestReladomoRuntimeConfiguration.xml")
            .transactionTimeout(5, TimeUnit.MINUTES);

    protected Client getClient(String clientName)
    {
        JerseyClientConfiguration jerseyClientConfiguration = new JerseyClientConfiguration();
        jerseyClientConfiguration.setTimeout(Duration.minutes(5));

        return new JerseyClientBuilder(RULE.getEnvironment())
                .using(jerseyClientConfiguration)
                .build(clientName);
    }

    @Before
    public void bootstrap()
    {
        KlassBootstrappedMetaModelApplication application = RULE.getApplication();

        KlassBootstrapWriter klassBootstrapWriter = new KlassBootstrapWriter(
                application.getDomainModel(),
                application.getDataStore());
        klassBootstrapWriter.bootstrapMetaModel();
    }

    @Test
    public void getAllMeta() throws JSONException
    {
        Client client = this.getClient(
                "klass.model.meta.domain.dropwizard.test.ProjectionResourceManualTest.getAllMeta");

        Response response = client.target(
                String.format("http://localhost:%d/api/meta/projection", RULE.getLocalPort()))
                .request()
                .get();

        this.assertResponseStatus(response, Status.OK);

        String jsonResponse = response.readEntity(String.class);
        //language=JSON
        String expected = "[\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"EnumerationProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCode\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCodeWithInference\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"enumerationLiterals\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"prettyName\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"sourceCode\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"sourceCodeWithInference\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"EnumerationSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"enumerationLiterals\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"prettyName\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"InterfaceProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCode\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCodeWithInference\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superInterfaces\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"superInterface\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"packageName\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionAssociationEnd\",\n"
                + "                \"name\": \"superInterfaces\",\n"
                + "                \"children\": [\n"
                + "                  {\n"
                + "                    \"_type\": \"ProjectionAssociationEnd\",\n"
                + "                    \"name\": \"superInterface\",\n"
                + "                    \"children\": [\n"
                + "                      {\n"
                + "                        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                        \"name\": \"name\"\n"
                + "                      },\n"
                + "                      {\n"
                + "                        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                        \"name\": \"packageName\"\n"
                + "                      }\n"
                + "                    ]\n"
                + "                  }\n"
                + "                ]\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"classifierModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"primitiveProperties\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"primitiveType\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"optional\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"id\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"propertyModifiers\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"inferred\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"ordinal\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"minLengthValidation\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"number\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"maxLengthValidation\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"number\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"minValidation\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"number\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"maxValidation\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"number\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"enumerationProperties\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"optional\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"key\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"enumeration\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"inferred\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"propertyModifiers\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"inferred\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"ordinal\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"minLengthValidation\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"number\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"maxLengthValidation\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"number\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"InterfaceSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superInterfaces\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"superInterface\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"classifierModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"primitiveProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"PrimitivePropertySummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"enumerationProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"EnumerationPropertySummaryProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"DataTypePropertyProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"primitiveType\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"optional\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"key\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"id\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"enumeration\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"propertyModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"PrimitivePropertyProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"primitiveType\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"optional\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"key\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"id\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"propertyModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"PrimitivePropertySummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"primitiveType\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"optional\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"key\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"id\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"propertyModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"EnumerationPropertyProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"optional\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"key\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"enumeration\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"propertyModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"EnumerationPropertySummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"optional\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"key\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"enumeration\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"propertyModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"minLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"maxLengthValidation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"number\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ClassProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCode\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCodeWithInference\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superClass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"packageName\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"superClass\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"packageName\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"superInterfaces\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionAssociationEnd\",\n"
                + "                \"name\": \"superInterface\",\n"
                + "                \"children\": [\n"
                + "                  {\n"
                + "                    \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                    \"name\": \"name\"\n"
                + "                  },\n"
                + "                  {\n"
                + "                    \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                    \"name\": \"packageName\"\n"
                + "                  }\n"
                + "                ]\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superInterfaces\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"superInterface\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"packageName\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionAssociationEnd\",\n"
                + "                \"name\": \"superInterfaces\",\n"
                + "                \"children\": [\n"
                + "                  {\n"
                + "                    \"_type\": \"ProjectionAssociationEnd\",\n"
                + "                    \"name\": \"superInterface\",\n"
                + "                    \"children\": [\n"
                + "                      {\n"
                + "                        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                        \"name\": \"name\"\n"
                + "                      },\n"
                + "                      {\n"
                + "                        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                        \"name\": \"packageName\"\n"
                + "                      }\n"
                + "                    ]\n"
                + "                  }\n"
                + "                ]\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"classifierModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"primitiveProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"PrimitivePropertyProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"enumerationProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"EnumerationPropertyProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"AssociationEndProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ClassSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superClass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superInterfaces\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"superInterface\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"classifierModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"primitiveProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"PrimitivePropertySummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"enumerationProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"EnumerationPropertySummaryProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ClassifierSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superClass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"superInterfaces\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"superInterface\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"classifierModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"primitiveProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"PrimitivePropertySummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"enumerationProperties\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"EnumerationPropertySummaryProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"AssociationEndProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCode\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCodeWithInference\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"direction\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"multiplicity\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"owningClass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"packageName\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"resultType\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"packageName\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"owningAssociation\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"associationEndModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"inferred\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"ordinal\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"AssociationEndSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"multiplicity\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"resultType\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"associationEndModifiers\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"orderBys\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionProjectionReference\",\n"
                + "            \"name\": \"thisMemberReferencePath\",\n"
                + "            \"projection\": {\n"
                + "              \"name\": \"MemberReferencePathSummaryProjection\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"orderByDirection\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"AssociationProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"inferred\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"ordinal\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCode\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"sourceCodeWithInference\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"AssociationEndProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"criteria\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"CriteriaProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"AssociationSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"AssociationEndSummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"criteria\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"CriteriaSummaryProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"MemberReferencePathProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"klass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"associationEnd\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"MemberReferencePathSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"klass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"associationEnd\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ExpressionValueProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"klass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"associationEnd\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"parameter\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"enumeration\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"primitiveType\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"multiplicity\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ExpressionValueSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"klass\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"associationEnds\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"associationEnd\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"dataTypeProperty\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"parameter\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"CriteriaProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"left\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"CriteriaProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"right\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"CriteriaProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"operator\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"sourceExpressionValue\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"ExpressionValueProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"targetExpressionValue\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"ExpressionValueProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"memberReferencePath\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"MemberReferencePathProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"CriteriaSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"left\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"CriteriaSummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"right\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"CriteriaSummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"operator\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"sourceExpressionValue\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"ExpressionValueSummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"targetExpressionValue\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"ExpressionValueSummaryProjection\"\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"memberReferencePath\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"MemberReferencePathSummaryProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ProjectionElementProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"projection\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"children\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"ProjectionElementSummaryProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ProjectionElementSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"projection\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"name\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionProjectionReference\",\n"
                + "        \"name\": \"children\",\n"
                + "        \"projection\": {\n"
                + "          \"name\": \"ProjectionElementSummaryProjection\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ServiceGroupProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"urls\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"url\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"services\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"verb\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"serviceMultiplicity\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionAssociationEnd\",\n"
                + "                \"name\": \"projection\",\n"
                + "                \"children\": [\n"
                + "                  {\n"
                + "                    \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                    \"name\": \"name\"\n"
                + "                  }\n"
                + "                ]\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionProjectionReference\",\n"
                + "                \"name\": \"queryCriteria\",\n"
                + "                \"projection\": {\n"
                + "                  \"name\": \"CriteriaSummaryProjection\"\n"
                + "                }\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionProjectionReference\",\n"
                + "                \"name\": \"authorizeCriteria\",\n"
                + "                \"projection\": {\n"
                + "                  \"name\": \"CriteriaSummaryProjection\"\n"
                + "                }\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionProjectionReference\",\n"
                + "                \"name\": \"validateCriteria\",\n"
                + "                \"projection\": {\n"
                + "                  \"name\": \"CriteriaSummaryProjection\"\n"
                + "                }\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionProjectionReference\",\n"
                + "                \"name\": \"conflictCriteria\",\n"
                + "                \"projection\": {\n"
                + "                  \"name\": \"CriteriaSummaryProjection\"\n"
                + "                }\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  {\n"
                + "    \"_type\": \"ServiceProjection\",\n"
                + "    \"name\": \"ServiceGroupSummaryProjection\",\n"
                + "    \"packageName\": \"klass.model.meta.domain\",\n"
                + "    \"children\": [\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"name\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "        \"name\": \"packageName\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"_type\": \"ProjectionAssociationEnd\",\n"
                + "        \"name\": \"urls\",\n"
                + "        \"children\": [\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "            \"name\": \"url\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"_type\": \"ProjectionAssociationEnd\",\n"
                + "            \"name\": \"services\",\n"
                + "            \"children\": [\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"verb\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                \"name\": \"serviceMultiplicity\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionAssociationEnd\",\n"
                + "                \"name\": \"projection\",\n"
                + "                \"children\": [\n"
                + "                  {\n"
                + "                    \"_type\": \"ProjectionDataTypeProperty\",\n"
                + "                    \"name\": \"name\"\n"
                + "                  }\n"
                + "                ]\n"
                + "              },\n"
                + "              {\n"
                + "                \"_type\": \"ProjectionProjectionReference\",\n"
                + "                \"name\": \"queryCriteria\",\n"
                + "                \"projection\": {\n"
                + "                  \"name\": \"CriteriaSummaryProjection\"\n"
                + "                }\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  }\n"
                + "]";
        JSONAssert.assertEquals(expected, jsonResponse, JSONCompareMode.STRICT);
    }

    public void assertResponseStatus(@Nonnull Response response, Status status)
    {
        response.bufferEntity();
        String entityAsString = response.readEntity(String.class);
        assertThat(entityAsString, response.getStatusInfo(), is(status));
    }
}
