package cool.klass.generator.grahql.schema;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.nio.file.Path;
import java.util.Objects;

import javax.annotation.Nonnull;

import cool.klass.model.meta.domain.api.Classifier;
import cool.klass.model.meta.domain.api.DomainModel;
import cool.klass.model.meta.domain.api.TopLevelElement;

public class GraphQLSchemaGenerator
{
    @Nonnull
    private final DomainModel domainModel;
    @Nonnull
    private final String      rootPackageName;
    @Nonnull
    private final String      applicationName;

    public GraphQLSchemaGenerator(
            @Nonnull DomainModel domainModel,
            @Nonnull String rootPackageName,
            @Nonnull String applicationName)
    {
        this.domainModel     = Objects.requireNonNull(domainModel);
        this.rootPackageName = Objects.requireNonNull(rootPackageName);
        this.applicationName = Objects.requireNonNull(applicationName);
    }

    public void writeSchemaFiles(@Nonnull Path outputPath)
    {
        String orderBySourceCode = this.domainModel
                .getClassifiers()
                .collect(this::getOrderBySourceCode)
                .makeString("");

        String topLevelElementsCode = this.domainModel
                .getTopLevelElements()
                .collect(this::getSourceCode)
                .makeString("");

        //language=GraphQL
        String sourceCode = ""
                + "# Generated by cool.klass.generator.grahql.schema.GraphQLSchemaGenerator\n"
                + "\n"
                + "# Order Bys\n"
                + orderBySourceCode
                + "\n"
                + "# Top Level Elements\n"
                + topLevelElementsCode;

        Path schemaOutputPath = this.getOutputPath(outputPath);
        this.printStringToFile(schemaOutputPath, sourceCode);
    }

    @Nonnull
    private Path getOutputPath(@Nonnull Path outputPath)
    {
        String packageRelativePath = this.rootPackageName.replaceAll("\\.", "/");
        Path outputDirectory = outputPath
                .resolve(packageRelativePath)
                .resolve("graphql")
                .resolve("schema");
        outputDirectory.toFile().mkdirs();
        String fileName = this.applicationName + ".graphqls";
        return outputDirectory.resolve(fileName);
    }

    private String getOrderBySourceCode(Classifier classifier)
    {
        //language=GraphQL
        return "input _" + classifier.getName() + "OrderBy {\n"
                + "    attribute: _" + classifier.getName() + "Finder\n"
                + "    direction: _OrderByDirection\n"
                + "}\n\n";
    }

    private String getSourceCode(@Nonnull TopLevelElement topLevelElement)
    {
        var visitor = new GraphQLElementToSchemaSourceVisitor();
        topLevelElement.visit(visitor);
        return visitor.getSourceCode();
    }

    private void printStringToFile(@Nonnull Path path, String contents)
    {
        try (var printStream = new PrintStream(new FileOutputStream(path.toFile())))
        {
            printStream.print(contents);
        }
        catch (FileNotFoundException e)
        {
            throw new RuntimeException(e);
        }
    }
}
