package cool.klass.generator.grahql.schema;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.nio.file.Path;
import java.util.Objects;

import javax.annotation.Nonnull;

import cool.klass.model.converter.graphql.schema.writer.KlassGraphQLModelConverter;
import cool.klass.model.graphql.domain.GraphQLDomainModel;
import cool.klass.model.graphql.domain.GraphQLElement;
import cool.klass.model.meta.domain.api.Classifier;
import cool.klass.model.meta.domain.api.DomainModel;
import cool.klass.model.meta.domain.api.PrimitiveType;
import cool.klass.model.meta.domain.api.property.DataTypeProperty;

public class GraphQLSchemaGenerator
{
    @Nonnull
    private final DomainModel domainModel;
    @Nonnull
    private final String      rootPackageName;
    @Nonnull
    private final String      applicationName;

    public GraphQLSchemaGenerator(
            @Nonnull DomainModel domainModel,
            @Nonnull String rootPackageName,
            @Nonnull String applicationName)
    {
        this.domainModel     = Objects.requireNonNull(domainModel);
        this.rootPackageName = Objects.requireNonNull(rootPackageName);
        this.applicationName = Objects.requireNonNull(applicationName);
    }

    public void writeSchemaFiles(@Nonnull Path outputPath)
    {
        KlassGraphQLModelConverter klassGraphQLModelConverter = new KlassGraphQLModelConverter(this.domainModel);
        GraphQLDomainModel         graphQLDomainModel         = klassGraphQLModelConverter.convert();

        String scalarsSourceCode = this.getScalarsSourceCode();

        String topLevelElementsCode = graphQLDomainModel.getTopLevelElements()
                .collect(this::getSourceCode)
                .makeString("");

        String sourceCode = ""
                + "# Generated by cool.klass.generator.grahql.schema.GraphQLSchemaGenerator\n"
                + "\n"
                + "schema {\n"
                + "    query: Query\n"
                + "}\n"
                + "\n"
                + scalarsSourceCode
                + "\n"
                + topLevelElementsCode;

        Path schemaOutputPath = this.getOutputPath(outputPath);
        this.printStringToFile(schemaOutputPath, sourceCode);
    }

    @Nonnull
    private Path getOutputPath(@Nonnull Path outputPath)
    {
        String packageRelativePath = this.rootPackageName.replaceAll("\\.", "/");
        Path outputDirectory = outputPath
                .resolve(packageRelativePath)
                .resolve("graphql")
                .resolve("schema");
        outputDirectory.toFile().mkdirs();
        String fileName = this.applicationName + ".graphqls";
        return outputDirectory.resolve(fileName);
    }

    private String getScalarsSourceCode()
    {
        return this.getTemporalScalarsSourceCode() + this.getPrimitiveScalarsSourceCode();
    }

    private String getTemporalScalarsSourceCode()
    {
        boolean isTemporal = this.domainModel
                .getClassifiers()
                .anySatisfy(Classifier::isTemporal);

        if (isTemporal)
        {
            return ""
                    + "scalar Instant\n"
                    + "scalar TemporalInstant\n"
                    + "scalar TemporalRange\n";
        }

        return "";
    }

    private String getPrimitiveScalarsSourceCode()
    {
        boolean containsLong = this.domainModel
                .getClassifiers()
                .asLazy()
                .flatCollect(Classifier::getDeclaredDataTypeProperties)
                .collect(DataTypeProperty::getType)
                .contains(PrimitiveType.LONG);

        return containsLong ? "scalar Long\n" : "";
    }

    private String getSourceCode(@Nonnull GraphQLElement graphQLElement)
    {
        GraphQLElementToSchemaSourceVisitor visitor = new GraphQLElementToSchemaSourceVisitor();
        graphQLElement.visit(visitor);
        return visitor.getSourceCode();
    }

    private void printStringToFile(@Nonnull Path path, String contents)
    {
        try (PrintStream printStream = new PrintStream(new FileOutputStream(path.toFile())))
        {
            printStream.print(contents);
        }
        catch (FileNotFoundException e)
        {
            throw new RuntimeException(e);
        }
    }
}
