package cool.klass.test;

import java.sql.Timestamp;

import com.gs.fw.common.mithra.util.DefaultInfinityTimestamp;
import cool.klass.test.reladomo.readable.ClassWithDerivedProperty;

/**
 * Auto-generated by {@link cool.klass.generator.reladomo.concrete.ReladomoConcreteClassGenerator}
 */
public class ClassWithDerivedProperty
        extends ClassWithDerivedPropertyAbstract
        implements ReladomoReadableClassWithDerivedProperty
{
    public ClassWithDerivedProperty(Timestamp system)
    {
        super(system);
        // You must not modify this constructor. Mithra calls this internally.
        // You can call this constructor. You can also add new constructors.
    }

    public ClassWithDerivedProperty()
    {
        this(DefaultInfinityTimestamp.getDefaultInfinity());
    }

    @Override
    public String getDerivedRequiredString()
    {
        // TODO implement derived property: derivedRequiredString
        return "ClassWithDerivedProperty derivedRequiredString 1 \u261D";
    }

    @Override
    public int getDerivedRequiredInteger()
    {
        // TODO implement derived property: derivedRequiredInteger
        return 1;
    }

    @Override
    public long getDerivedRequiredLong()
    {
        // TODO implement derived property: derivedRequiredLong
        return 100000000000L;
    }

    @Override
    public double getDerivedRequiredDouble()
    {
        // TODO implement derived property: derivedRequiredDouble
        return 1.0123456789;
    }

    @Override
    public float getDerivedRequiredFloat()
    {
        // TODO implement derived property: derivedRequiredFloat
        return 1.0123457f;
    }

    @Override
    public boolean getDerivedRequiredBoolean()
    {
        // TODO implement derived property: derivedRequiredBoolean
        return true;
    }

    @Override
    public Timestamp getDerivedRequiredInstant()
    {
        // TODO implement derived property: derivedRequiredInstant
        return Instant.parse("1999-12-31T23:59:00Z");
    }

    @Override
    public Date getDerivedRequiredLocalDate()
    {
        // TODO implement derived property: derivedRequiredLocalDate
        return LocalDate.parse("1999-12-31");
    }

    @Override
    public String getDerivedOptionalString()
    {
        // TODO implement derived property: derivedOptionalString
        return "ClassWithDerivedProperty derivedOptionalString 1 \u261D";
    }

    @Override
    public int getDerivedOptionalInteger()
    {
        // TODO implement derived property: derivedOptionalInteger
        return 1;
    }

    @Override
    public long getDerivedOptionalLong()
    {
        // TODO implement derived property: derivedOptionalLong
        return 100000000000L;
    }

    @Override
    public double getDerivedOptionalDouble()
    {
        // TODO implement derived property: derivedOptionalDouble
        return 1.0123456789;
    }

    @Override
    public float getDerivedOptionalFloat()
    {
        // TODO implement derived property: derivedOptionalFloat
        return 1.0123457f;
    }

    @Override
    public boolean getDerivedOptionalBoolean()
    {
        // TODO implement derived property: derivedOptionalBoolean
        return true;
    }

    @Override
    public Timestamp getDerivedOptionalInstant()
    {
        // TODO implement derived property: derivedOptionalInstant
        return Instant.parse("1999-12-31T23:59:00Z");
    }

    @Override
    public Date getDerivedOptionalLocalDate()
    {
        // TODO implement derived property: derivedOptionalLocalDate
        return LocalDate.parse("1999-12-31");
    }
}
