package cool.klass.generator.klass.html;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.nio.file.Path;
import java.util.Objects;

import javax.annotation.Nonnull;

import cool.klass.model.meta.domain.api.DomainModel;
import cool.klass.model.meta.domain.api.PackageableElement;
import org.eclipse.collections.api.RichIterable;
import org.eclipse.collections.api.tuple.Pair;

public class KlassHtmlGenerator
{
    @Nonnull
    private final DomainModel domainModel;

    public KlassHtmlGenerator(@Nonnull DomainModel domainModel)
    {
        this.domainModel = Objects.requireNonNull(domainModel);
    }

    public void writeHtmlFiles(@Nonnull Path outputPath)
    {
        this.domainModel
                .getTopLevelElements()
                .groupBy(PackageableElement::getPackageName)
                .keyMultiValuePairsView()
                .forEachWith(this::writeFile, outputPath);
    }

    private void writeFile(Pair<String, RichIterable<PackageableElement>> packagePair, Path outputPath)
    {
        String                           fullyQualifiedPackage = packagePair.getOne();
        RichIterable<PackageableElement> topLevelElements      = packagePair.getTwo();

        Path   klassOutputPath      = this.getOutputPath(outputPath, fullyQualifiedPackage);
        String projectionSourceCode = this.getTopLevelElementSourceCode(topLevelElements, fullyQualifiedPackage);

        this.printStringToFile(klassOutputPath, projectionSourceCode);
    }

    @Nonnull
    private Path getOutputPath(
            @Nonnull Path outputPath,
            @Nonnull String fullyQualifiedPackage)
    {
        String packageRelativePath = fullyQualifiedPackage.replaceAll("\\.", "/");
        Path   klassDirectory      = outputPath.resolve(packageRelativePath);
        String fileName            = fullyQualifiedPackage + ".klass";

        klassDirectory.toFile().mkdirs();
        return klassDirectory.resolve(fileName);
    }

    @Nonnull
    private String getTopLevelElementSourceCode(
            @Nonnull RichIterable<PackageableElement> topLevelElements,
            @Nonnull String fullyQualifiedPackage)
    {
        String sourceCode = topLevelElements
                .collect(KlassHtmlGenerator::getSourceCode)
                .makeString("\n\n");

        //language=Klass
        return "package " + fullyQualifiedPackage + ".inference\n"
                + "\n"
                + "/*\n"
                + " * Auto-generated by {@link cool.klass.generator.klass.html.KlassHtmlGenerator}\n"
                + " */\n"
                + "\n"
                + sourceCode;
    }

    private static String getSourceCode(PackageableElement packageableElement)
    {
        return "";
    }

    private void printStringToFile(@Nonnull Path path, String contents)
    {
        try (PrintStream printStream = new PrintStream(new FileOutputStream(path.toFile())))
        {
            printStream.print(contents);
        }
        catch (FileNotFoundException e)
        {
            throw new RuntimeException(e);
        }
    }
}
