package cool.klass.generator.reladomo.readable;

import java.util.Optional;

import cool.klass.model.converter.compiler.CompilationResult;
import cool.klass.model.converter.compiler.CompilationUnit;
import cool.klass.model.converter.compiler.KlassCompiler;
import cool.klass.model.converter.compiler.annotation.RootCompilerAnnotation;
import cool.klass.model.meta.domain.api.Klass;
import cool.klass.model.meta.domain.api.source.DomainModelWithSourceCode;
import io.liftwizard.junit.rule.log.marker.LogMarkerTestRule;
import org.eclipse.collections.api.list.ImmutableList;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestRule;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.Assert.fail;

public class ReladomoReadableInterfaceGeneratorTest
{
    @Rule
    public final TestRule logMarkerTestRule = new LogMarkerTestRule();

    @Test
    public void smokeTest()
    {
        //<editor-fold desc="sourceCode">
        //language=Klass
        String klassSourceCode = """
                package cool.klass.test

                class ClassWithDerivedProperty
                {
                    key                : String key;

                    derivedRequiredString      : String    derived;
                    derivedRequiredInteger     : Integer   derived;
                    derivedRequiredLong        : Long      derived;
                    derivedRequiredDouble      : Double    derived;
                    derivedRequiredFloat       : Float     derived;
                    derivedRequiredBoolean     : Boolean   derived;
                    derivedRequiredInstant     : Instant   derived;
                    derivedRequiredLocalDate   : LocalDate derived;

                    derivedOptionalString      : String    ? derived;
                    derivedOptionalInteger     : Integer   ? derived;
                    derivedOptionalLong        : Long      ? derived;
                    derivedOptionalDouble      : Double    ? derived;
                    derivedOptionalFloat       : Float     ? derived;
                    derivedOptionalBoolean     : Boolean   ? derived;
                    derivedOptionalInstant     : Instant   ? derived;
                    derivedOptionalLocalDate   : LocalDate ? derived;
                }
                """;
        //</editor-fold>

        CompilationUnit compilationUnit = CompilationUnit.createFromText(
                0,
                Optional.empty(),
                "example.klass",
                klassSourceCode);
        KlassCompiler     compiler          = new KlassCompiler(compilationUnit);
        CompilationResult compilationResult = compiler.compile();

        if (compilationResult.domainModelWithSourceCode().isEmpty())
        {
            ImmutableList<RootCompilerAnnotation> compilerAnnotations     = compilationResult.compilerAnnotations();
            String                                message                 = compilerAnnotations.makeString("\n");
            fail(message);
        }
        else
        {
            DomainModelWithSourceCode domainModel = compilationResult.domainModelWithSourceCode().get();
            assertThat(domainModel, notNullValue());

            ReladomoReadableInterfaceGenerator generator = new ReladomoReadableInterfaceGenerator(domainModel);

            Klass  klass          = domainModel.getClassByName("ClassWithDerivedProperty");
            String javaSourceCode = generator.getSourceCode(klass);

            //<editor-fold desc="expected java code">
            //language=JAVA
            String expectedSourceCode = """
                    package cool.klass.test.reladomo.readable;

                    import javax.annotation.*;
                    import java.sql.*;
                    import java.time.*;

                    /**
                     * Auto-generated by {@link cool.klass.generator.reladomo.readable.ReladomoReadableInterfaceGenerator}
                     */
                    public interface ReladomoReadableClassWithDerivedProperty
                    {
                        // key
                        @Nonnull
                        String getKey();

                        // derived
                        @Nonnull
                        String getDerivedRequiredString();

                        // derived
                        @Nonnull
                        int getDerivedRequiredInteger();

                        // derived
                        @Nonnull
                        long getDerivedRequiredLong();

                        // derived
                        @Nonnull
                        double getDerivedRequiredDouble();

                        // derived
                        @Nonnull
                        float getDerivedRequiredFloat();

                        // derived
                        @Nonnull
                        boolean isDerivedRequiredBoolean();

                        // derived
                        @Nonnull
                        Timestamp getDerivedRequiredInstant();

                        // derived
                        @Nonnull
                        Date getDerivedRequiredLocalDate();

                        // derived
                        String getDerivedOptionalString();

                        // derived
                        int getDerivedOptionalInteger();

                        // derived
                        long getDerivedOptionalLong();

                        // derived
                        double getDerivedOptionalDouble();

                        // derived
                        float getDerivedOptionalFloat();

                        // derived
                        boolean isDerivedOptionalBoolean();

                        // derived
                        Timestamp getDerivedOptionalInstant();

                        // derived
                        Date getDerivedOptionalLocalDate();
                    }
                    """;
            //</editor-fold>

            assertThat(javaSourceCode, javaSourceCode, is(expectedSourceCode));
        }
    }
}
